# STATUS MODELS

In [ ]:
sampled_data['loan_status'].value_counts()

loan_status
0    2397894
1     202441
Name: count, dtype: int64

In [ ]:
sampled_data['loan_status'].value_counts()[0] / sampled_data['loan_status'].value_counts()[1]

11.844902959380757

In [ ]:
model_2 = cb.CatBoostClassifier(
    iterations=2500
    cat_features=categorical_features,
    eval_metric='Logloss',
    early_stopping_rounds=500,
    random_state=42,
    scale_pos_weight=9
)

In [ ]:
start_time = time.time()
model_2.fit(
    X_train, 
    y_train, 
    eval_set=(X_validation, y_validation), 
    verbose=100,
    plot=True,
    early_stopping_rounds=100
)
end_time = time.time()
training_duration = end_time - start_time
print(f"Training completed in {training_duration:.2f} seconds")

y_pred = model_2.predict(X_test)
y_pred_proba = model_2.predict_proba(X_test)[:, 1]

report = classification_report(y_test, y_pred, target_names=['Class 0', 'Class 1'])

print(report)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Learning rate set to 0.114473
0:	learn: 0.5706903	test: 0.5706431	best: 0.5706431 (0)	total: 508ms	remaining: 21m 9s
100:	learn: 0.2230370	test: 0.2226688	best: 0.2226688 (100)	total: 52.5s	remaining: 20m 47s
200:	learn: 0.2140999	test: 0.2140446	best: 0.2140446 (200)	total: 2m 31s	remaining: 28m 54s
300:	learn: 0.2105588	test: 0.2110770	best: 0.2110770 (300)	total: 3m 38s	remaining: 26m 34s
400:	learn: 0.2078532	test: 0.2094429	best: 0.2094429 (400)	total: 5m 1s	remaining: 26m 19s
500:	learn: 0.2058772	test: 0.2082893	best: 0.2082893 (500)	total: 6m 27s	remaining: 25m 44s
600:	learn: 0.2042001	test: 0.2075405	best: 0.2075405 (600)	total: 7m 47s	remaining: 24m 38s
700:	learn: 0.2026625	test: 0.2071515	best: 0.2071515 (700)	total: 9m 5s	remaining: 23m 19s
800:	learn: 0.2013127	test: 0.2068420	best: 0.2068420 (800)	total: 10m 31s	remaining: 22m 19s
900:	learn: 0.2001036	test: 0.2066661	best: 0.2066536 (896)	total: 11m 57s	remaining: 21m 13s
1000:	learn: 0.1989671	test: 0.2064457	best: 0.

In [ ]:
model_3 = cb.CatBoostClassifier(
    cat_features=categorical_features,
    eval_metric='Logloss',
    early_stopping_rounds=50,
    random_state=42,
    scale_pos_weight=5
)

In [ ]:
start_time = time.time()
model_3.fit(
    X_train, 
    y_train, 
    eval_set=(X_validation, y_validation), 
    verbose=100,
    plot=True,
    early_stozddpping_rounds=100
)
end_time = time.time()
training_duration = end_time - start_time
print(f"Training completed in {training_duration:.2f} seconds")

y_pred = model_3.predict(X_test)
y_pred_proba = model_3.predict_proba(X_test)[:, 1]

report = classification_report(y_test, y_pred, target_names=['Class 0', 'Class 1'])

print(report)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Learning rate set to 0.170532
0:	learn: 0.5028796	test: 0.5028489	best: 0.5028489 (0)	total: 593ms	remaining: 9m 52s
100:	learn: 0.1973001	test: 0.1969415	best: 0.1969415 (100)	total: 1m	remaining: 8m 57s
200:	learn: 0.1910676	test: 0.1914255	best: 0.1914255 (200)	total: 2m 21s	remaining: 9m 21s
300:	learn: 0.1881866	test: 0.1894987	best: 0.1894987 (300)	total: 3m 38s	remaining: 8m 28s
400:	learn: 0.1861810	test: 0.1884183	best: 0.1884183 (400)	total: 4m 58s	remaining: 7m 26s
500:	learn: 0.1846975	test: 0.1879094	best: 0.1879090 (499)	total: 6m 23s	remaining: 6m 21s
600:	learn: 0.1832979	test: 0.1875289	best: 0.1875288 (599)	total: 7m 49s	remaining: 5m 11s
700:	learn: 0.1821951	test: 0.1873420	best: 0.1873350 (689)	total: 9m 6s	remaining: 3m 53s
800:	learn: 0.1809671	test: 0.1871843	best: 0.1871843 (800)	total: 10m 32s	remaining: 2m 37s
900:	learn: 0.1798351	test: 0.1871120	best: 0.1871053 (891)	total: 11m 56s	remaining: 1m 18s
999:	learn: 0.1789600	test: 0.1870319	best: 0.1870273 (993

In [ ]:
model_4 = cb.CatBoostClassifier(
    cat_features=categorical_features,
    eval_metric='Logloss',
    early_stopping_rounds=50,
    random_state=42,
    scale_pos_weight=5
)

In [ ]:
start_time = time.time()
model_3.fit(
    X_train, 
    y_train, 
    eval_set=(X_validation, y_validation), 
    verbose=100,
    plot=True,
    early_stopping_rounds=100
)
end_time = time.time()
training_duration = end_time - start_time
print(f"Training completed in {training_duration:.2f} seconds")

y_pred = model_3.predict(X_test)
y_pred_proba = model_3.predict_proba(X_test)[:, 1]

report = classification_report(y_test, y_pred, target_names=['Class 0', 'Class 1'])

print(report)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Learning rate set to 0.170532
0:	learn: 0.5028796	test: 0.5028489	best: 0.5028489 (0)	total: 593ms	remaining: 9m 52s
100:	learn: 0.1973001	test: 0.1969415	best: 0.1969415 (100)	total: 1m	remaining: 8m 57s
200:	learn: 0.1910676	test: 0.1914255	best: 0.1914255 (200)	total: 2m 21s	remaining: 9m 21s
300:	learn: 0.1881866	test: 0.1894987	best: 0.1894987 (300)	total: 3m 38s	remaining: 8m 28s
400:	learn: 0.1861810	test: 0.1884183	best: 0.1884183 (400)	total: 4m 58s	remaining: 7m 26s
500:	learn: 0.1846975	test: 0.1879094	best: 0.1879090 (499)	total: 6m 23s	remaining: 6m 21s
600:	learn: 0.1832979	test: 0.1875289	best: 0.1875288 (599)	total: 7m 49s	remaining: 5m 11s
700:	learn: 0.1821951	test: 0.1873420	best: 0.1873350 (689)	total: 9m 6s	remaining: 3m 53s
800:	learn: 0.1809671	test: 0.1871843	best: 0.1871843 (800)	total: 10m 32s	remaining: 2m 37s
900:	learn: 0.1798351	test: 0.1871120	best: 0.1871053 (891)	total: 11m 56s	remaining: 1m 18s
999:	learn: 0.1789600	test: 0.1870319	best: 0.1870273 (993

In [ ]:
X_full = data.drop('loan_status', axis=1)  
y_pred_full = model_2.predict(X_full)
y_pred_proba_full = model_2.predict_proba(X_full)[:, 1]


In [ ]:
y_full = data['loan_status']  # Target variable
report_full = classification_report(y_full, y_pred_full, target_names=['Class 0', 'Class 1'])
print(report_full)

              precision    recall  f1-score   support

     Class 0       0.99      0.95      0.97  23978934
     Class 1       0.59      0.90      0.71   2024413

    accuracy                           0.94  26003347
   macro avg       0.79      0.92      0.84  26003347
weighted avg       0.96      0.94      0.95  26003347



# GRADE MODELS 

### Model 1

In [ ]:
model_1 = CatBoostClassifier(
    iterations=600,
    loss_function='MultiClass', 
    cat_features=cat_features,
    verbose=100,
    eval_metric='TotalF1',  
    auto_class_weights='Balanced',
    early_stopping_rounds=150
)

In [ ]:
model_1.fit(train_pool, eval_set=validation_pool, plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Learning rate set to 0.142882
0:	learn: 0.2999232	test: 0.2745249	best: 0.2745249 (0)	total: 317ms	remaining: 3m 9s
100:	learn: 0.5365817	test: 0.3762046	best: 0.3803602 (97)	total: 34.2s	remaining: 2m 49s
200:	learn: 0.6252253	test: 0.3746587	best: 0.3834560 (167)	total: 1m 8s	remaining: 2m 15s
300:	learn: 0.6725933	test: 0.3784021	best: 0.3834560 (167)	total: 1m 42s	remaining: 1m 41s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.3834560092
bestIteration = 167

Shrink model to first 168 iterations.


In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, recall_score, roc_auc_score

y_pred = model_1.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           A       0.63      0.76      0.69      2876
           B       0.50      0.47      0.49      4441
           C       0.47      0.31      0.37      4302
           D       0.29      0.26      0.27      2129
           E       0.20      0.31      0.24       893
           F       0.13      0.42      0.19       276
           G       0.07      0.16      0.09        83

    accuracy                           0.44     15000
   macro avg       0.32      0.38      0.34     15000
weighted avg       0.46      0.44      0.44     15000

[[2199  590   60   17    8    2    0]
 [1002 2103  882  295  113   36   10]
 [ 264 1179 1331  817  457  220   34]
 [  41  287  456  547  482  263   53]
 [   6   57   80  179  278  247   46]
 [   2    3   15   37   67  115   37]
 [   0    1    6    9   18   36   13]]


#### Model 1 Feature Importances

In [ ]:
model_1_fi_1 = model_1.get_feature_importance(prettified=True)
model_1_fi_loss = model_1.get_feature_importance(
    train_pool,
    'LossFunctionChange',
    prettified=True
)

In [ ]:
model_1_fi_1.tail(4)

Feature Id  Importances
52            pymnt_plan          0.0
53      application_type          0.0
54         hardship_flag          0.0
55  debt_settlement_flag          0.0

In [ ]:
model_1_fi_loss.tail(4)

Feature Id  Importances
52            pymnt_plan          0.0
53      application_type          0.0
54         hardship_flag          0.0
55  debt_settlement_flag          0.0

- Maybe drop these 4 ?

### Model 2

In [ ]:
model_1 = CatBoostClassifier(
    iterations=600,
    loss_function='MultiClass', 
    cat_features=cat_features,
    verbose=100,
    eval_metric='TotalF1',  
    auto_class_weights='Balanced',
    early_stopping_rounds=150
)

In [ ]:
model_2 = CatBoostClassifier(
    iterations=600,
    learning_rate=0.03,          
    depth=8,
    loss_function='MultiClass',
    eval_metric='TotalF1',
    cat_features=cat_features,
    auto_class_weights='Balanced',
    early_stopping_rounds=150,
    verbose=50
)

model_2.fit(train_pool, eval_set=validation_pool, plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.3201898	test: 0.2788386	best: 0.2788386 (0)	total: 618ms	remaining: 6m 10s
50:	learn: 0.4362773	test: 0.3562481	best: 0.3562481 (50)	total: 31.3s	remaining: 5m 37s
100:	learn: 0.4862432	test: 0.3645884	best: 0.3664766 (99)	total: 1m 3s	remaining: 5m 13s
150:	learn: 0.5233320	test: 0.3561004	best: 0.3693466 (107)	total: 1m 40s	remaining: 4m 58s
200:	learn: 0.5497616	test: 0.3658270	best: 0.3693466 (107)	total: 2m 12s	remaining: 4m 22s
250:	learn: 0.5721622	test: 0.3720376	best: 0.3740000 (241)	total: 2m 43s	remaining: 3m 46s
300:	learn: 0.5931872	test: 0.3748215	best: 0.3767354 (292)	total: 3m 14s	remaining: 3m 13s
350:	learn: 0.6108232	test: 0.3711746	best: 0.3771445 (302)	total: 3m 48s	remaining: 2m 41s
400:	learn: 0.6299781	test: 0.3704336	best: 0.3771445 (302)	total: 4m 21s	remaining: 2m 9s
450:	learn: 0.6482676	test: 0.3749342	best: 0.3787750 (434)	total: 4m 53s	remaining: 1m 36s
500:	learn: 0.6648098	test: 0.3776219	best: 0.3787750 (434)	total: 5m 21s	remaining: 1m 3s


In [ ]:
y_pred = model_2.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           A       0.62      0.77      0.69      2876
           B       0.50      0.48      0.49      4441
           C       0.48      0.33      0.39      4302
           D       0.30      0.28      0.29      2129
           E       0.21      0.34      0.26       893
           F       0.15      0.41      0.22       276
           G       0.08      0.10      0.09        83

    accuracy                           0.45     15000
   macro avg       0.33      0.38      0.35     15000
weighted avg       0.46      0.45      0.45     15000

[[2201  577   77   15    4    2    0]
 [1030 2114  878  294  100   25    0]
 [ 259 1187 1403  828  463  152   10]
 [  49  290  468  591  500  211   20]
 [   6   57   95  188  303  209   35]
 [   2    4   15   42   77  114   22]
 [   0    1    4    9   21   40    8]]


#### Model 2 Feature Importances

In [ ]:
model_2_fi_1 = model_2.get_feature_importance(prettified=True)
model_2_fi_loss = model_2.get_feature_importance(
    train_pool,
    'LossFunctionChange',
    prettified=True
)

In [ ]:
model_2_fi_1.head()

Feature Id  Importances
0                 term    11.498417
1      PCA_Component_2    10.342403
2      PCA_Component_3     7.103404
3      PCA_Component_5     6.911119
4  verification_status     4.781445

In [ ]:
model_2_fi_loss.head()

Feature Id  Importances
0              term     0.117731
1   PCA_Component_2     0.077398
2   PCA_Component_5     0.067554
3   PCA_Component_3     0.049376
4  PCA_Component_40     0.029133

In [ ]:
classes = np.unique(y_train)
weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train)
class_weights = dict(zip(classes, weights))

In [ ]:
class_weights

{'A': 0.7451564828614009,
 'B': 0.48255561453457513,
 'C': 0.49808238282611944,
 'D': 1.0068465565847764,
 'E': 2.3986567522187574,
 'F': 7.745933384972889,
 'G': 25.77319587628866}

In [ ]:
model_2 = CatBoostClassifier(
    iterations=600,
    learning_rate=0.03,
    depth=8,
    loss_function='MultiClass',
    eval_metric='TotalF1',
    cat_features=cat_features,
    class_weights=class_weights,  
    early_stopping_rounds=150,
    verbose=50
)

model_2.fit(train_pool, eval_set=validation_pool, plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.3201898	test: 0.2788386	best: 0.2788386 (0)	total: 610ms	remaining: 6m 5s
50:	learn: 0.4562487	test: 0.3593569	best: 0.3626243 (38)	total: 34.5s	remaining: 6m 11s
100:	learn: 0.5162280	test: 0.3695433	best: 0.3695433 (100)	total: 1m 8s	remaining: 5m 40s
150:	learn: 0.5517065	test: 0.3705792	best: 0.3774473 (120)	total: 1m 43s	remaining: 5m 8s
200:	learn: 0.5816587	test: 0.3685364	best: 0.3774473 (120)	total: 2m 19s	remaining: 4m 37s
250:	learn: 0.6042491	test: 0.3783754	best: 0.3818830 (243)	total: 2m 55s	remaining: 4m 3s
300:	learn: 0.6198970	test: 0.3772371	best: 0.3828191 (291)	total: 3m 30s	remaining: 3m 29s
350:	learn: 0.6378978	test: 0.3763504	best: 0.3828191 (291)	total: 4m 6s	remaining: 2m 54s
400:	learn: 0.6540609	test: 0.3760672	best: 0.3839273 (390)	total: 4m 40s	remaining: 2m 19s
450:	learn: 0.6695487	test: 0.3804665	best: 0.3839273 (390)	total: 5m 12s	remaining: 1m 43s
500:	learn: 0.6830140	test: 0.3774670	best: 0.3852337 (493)	total: 5m 43s	remaining: 1m 7s
55

In [ ]:
y_pred = model_2.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           A       0.63      0.77      0.69      2876
           B       0.50      0.48      0.49      4441
           C       0.47      0.33      0.39      4302
           D       0.30      0.28      0.29      2129
           E       0.22      0.38      0.28       893
           F       0.16      0.40      0.23       276
           G       0.14      0.12      0.13        83

    accuracy                           0.45     15000
   macro avg       0.35      0.39      0.36     15000
weighted avg       0.46      0.45      0.45     15000

[[2211  572   72   15    5    1    0]
 [1009 2127  905  282   97   21    0]
 [ 250 1175 1400  846  488  136    7]
 [  44  287  471  601  502  211   13]
 [   6   56   94  187  337  191   22]
 [   2    4   16   44   81  111   18]
 [   0    1    4    9   20   39   10]]


- We can see weights automatic or not is the same. 
- Maybe we can tru oversampling the minority classes

In [ ]:
model_1 = CatBoostClassifier(
    iterations=600,
    loss_function='MultiClass', 
    cat_features=cat_features,
    verbose=100,
    eval_metric='TotalF1',  
    auto_class_weights='Balanced',
    early_stopping_rounds=150
)

In [ ]:
model_1.fit(train_pool, eval_set=validation_pool, plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Learning rate set to 0.142882
0:	learn: 0.2999232	test: 0.2745249	best: 0.2745249 (0)	total: 317ms	remaining: 3m 9s
100:	learn: 0.5365817	test: 0.3762046	best: 0.3803602 (97)	total: 34.2s	remaining: 2m 49s
200:	learn: 0.6252253	test: 0.3746587	best: 0.3834560 (167)	total: 1m 8s	remaining: 2m 15s
300:	learn: 0.6725933	test: 0.3784021	best: 0.3834560 (167)	total: 1m 42s	remaining: 1m 41s
Stopped by overfitting detector  (150 iterations wait)

bestTest = 0.3834560092
bestIteration = 167

Shrink model to first 168 iterations.


In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, recall_score, roc_auc_score

y_pred = model_1.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           A       0.63      0.76      0.69      2876
           B       0.50      0.47      0.49      4441
           C       0.47      0.31      0.37      4302
           D       0.29      0.26      0.27      2129
           E       0.20      0.31      0.24       893
           F       0.13      0.42      0.19       276
           G       0.07      0.16      0.09        83

    accuracy                           0.44     15000
   macro avg       0.32      0.38      0.34     15000
weighted avg       0.46      0.44      0.44     15000

[[2199  590   60   17    8    2    0]
 [1002 2103  882  295  113   36   10]
 [ 264 1179 1331  817  457  220   34]
 [  41  287  456  547  482  263   53]
 [   6   57   80  179  278  247   46]
 [   2    3   15   37   67  115   37]
 [   0    1    6    9   18   36   13]]


#### Model 1 Feature Importances

In [ ]:
model_1_fi_1 = model_1.get_feature_importance(prettified=True)
model_1_fi_loss = model_1.get_feature_importance(
    train_pool,
    'LossFunctionChange',
    prettified=True
)

In [ ]:
model_1_fi_1.tail(4)

Feature Id  Importances
52            pymnt_plan          0.0
53      application_type          0.0
54         hardship_flag          0.0
55  debt_settlement_flag          0.0

In [ ]:
model_1_fi_loss.tail(4)

Feature Id  Importances
52            pymnt_plan          0.0
53      application_type          0.0
54         hardship_flag          0.0
55  debt_settlement_flag          0.0

- Maybe drop these 4 ?

### Model 2

In [ ]:
model_1 = CatBoostClassifier(
    iterations=600,
    loss_function='MultiClass', 
    cat_features=cat_features,
    verbose=100,
    eval_metric='TotalF1',  
    auto_class_weights='Balanced',
    early_stopping_rounds=150
)

In [ ]:
model_2 = CatBoostClassifier(
    iterations=600,
    learning_rate=0.03,          
    depth=8,
    loss_function='MultiClass',
    eval_metric='TotalF1',
    cat_features=cat_features,
    auto_class_weights='Balanced',
    early_stopping_rounds=150,
    verbose=50
)

model_2.fit(train_pool, eval_set=validation_pool, plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.3201898	test: 0.2788386	best: 0.2788386 (0)	total: 618ms	remaining: 6m 10s
50:	learn: 0.4362773	test: 0.3562481	best: 0.3562481 (50)	total: 31.3s	remaining: 5m 37s
100:	learn: 0.4862432	test: 0.3645884	best: 0.3664766 (99)	total: 1m 3s	remaining: 5m 13s
150:	learn: 0.5233320	test: 0.3561004	best: 0.3693466 (107)	total: 1m 40s	remaining: 4m 58s
200:	learn: 0.5497616	test: 0.3658270	best: 0.3693466 (107)	total: 2m 12s	remaining: 4m 22s
250:	learn: 0.5721622	test: 0.3720376	best: 0.3740000 (241)	total: 2m 43s	remaining: 3m 46s
300:	learn: 0.5931872	test: 0.3748215	best: 0.3767354 (292)	total: 3m 14s	remaining: 3m 13s
350:	learn: 0.6108232	test: 0.3711746	best: 0.3771445 (302)	total: 3m 48s	remaining: 2m 41s
400:	learn: 0.6299781	test: 0.3704336	best: 0.3771445 (302)	total: 4m 21s	remaining: 2m 9s
450:	learn: 0.6482676	test: 0.3749342	best: 0.3787750 (434)	total: 4m 53s	remaining: 1m 36s
500:	learn: 0.6648098	test: 0.3776219	best: 0.3787750 (434)	total: 5m 21s	remaining: 1m 3s


In [ ]:
y_pred = model_2.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           A       0.62      0.77      0.69      2876
           B       0.50      0.48      0.49      4441
           C       0.48      0.33      0.39      4302
           D       0.30      0.28      0.29      2129
           E       0.21      0.34      0.26       893
           F       0.15      0.41      0.22       276
           G       0.08      0.10      0.09        83

    accuracy                           0.45     15000
   macro avg       0.33      0.38      0.35     15000
weighted avg       0.46      0.45      0.45     15000

[[2201  577   77   15    4    2    0]
 [1030 2114  878  294  100   25    0]
 [ 259 1187 1403  828  463  152   10]
 [  49  290  468  591  500  211   20]
 [   6   57   95  188  303  209   35]
 [   2    4   15   42   77  114   22]
 [   0    1    4    9   21   40    8]]


#### Model 2 Feature Importances

In [ ]:
model_2_fi_1 = model_2.get_feature_importance(prettified=True)
model_2_fi_loss = model_2.get_feature_importance(
    train_pool,
    'LossFunctionChange',
    prettified=True
)

In [ ]:
model_2_fi_1.head()

Feature Id  Importances
0                 term    11.498417
1      PCA_Component_2    10.342403
2      PCA_Component_3     7.103404
3      PCA_Component_5     6.911119
4  verification_status     4.781445

In [ ]:
model_2_fi_loss.head()

Feature Id  Importances
0              term     0.117731
1   PCA_Component_2     0.077398
2   PCA_Component_5     0.067554
3   PCA_Component_3     0.049376
4  PCA_Component_40     0.029133

In [ ]:
# Calculate class weights
classes = np.unique(y_train)
weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train)
class_weights = dict(zip(classes, weights))

In [ ]:
class_weights

{'A': 0.7451564828614009,
 'B': 0.48255561453457513,
 'C': 0.49808238282611944,
 'D': 1.0068465565847764,
 'E': 2.3986567522187574,
 'F': 7.745933384972889,
 'G': 25.77319587628866}

In [ ]:
model_2 = CatBoostClassifier(
    iterations=600,
    learning_rate=0.03,
    depth=8,
    loss_function='MultiClass',
    eval_metric='TotalF1',
    cat_features=cat_features,
    class_weights=class_weights,  
    early_stopping_rounds=150,
    verbose=50
)

model_2.fit(train_pool, eval_set=validation_pool, plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.3201898	test: 0.2788386	best: 0.2788386 (0)	total: 610ms	remaining: 6m 5s
50:	learn: 0.4562487	test: 0.3593569	best: 0.3626243 (38)	total: 34.5s	remaining: 6m 11s
100:	learn: 0.5162280	test: 0.3695433	best: 0.3695433 (100)	total: 1m 8s	remaining: 5m 40s
150:	learn: 0.5517065	test: 0.3705792	best: 0.3774473 (120)	total: 1m 43s	remaining: 5m 8s
200:	learn: 0.5816587	test: 0.3685364	best: 0.3774473 (120)	total: 2m 19s	remaining: 4m 37s
250:	learn: 0.6042491	test: 0.3783754	best: 0.3818830 (243)	total: 2m 55s	remaining: 4m 3s
300:	learn: 0.6198970	test: 0.3772371	best: 0.3828191 (291)	total: 3m 30s	remaining: 3m 29s
350:	learn: 0.6378978	test: 0.3763504	best: 0.3828191 (291)	total: 4m 6s	remaining: 2m 54s
400:	learn: 0.6540609	test: 0.3760672	best: 0.3839273 (390)	total: 4m 40s	remaining: 2m 19s
450:	learn: 0.6695487	test: 0.3804665	best: 0.3839273 (390)	total: 5m 12s	remaining: 1m 43s
500:	learn: 0.6830140	test: 0.3774670	best: 0.3852337 (493)	total: 5m 43s	remaining: 1m 7s
55

In [ ]:
y_pred = model_2.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           A       0.63      0.77      0.69      2876
           B       0.50      0.48      0.49      4441
           C       0.47      0.33      0.39      4302
           D       0.30      0.28      0.29      2129
           E       0.22      0.38      0.28       893
           F       0.16      0.40      0.23       276
           G       0.14      0.12      0.13        83

    accuracy                           0.45     15000
   macro avg       0.35      0.39      0.36     15000
weighted avg       0.46      0.45      0.45     15000

[[2211  572   72   15    5    1    0]
 [1009 2127  905  282   97   21    0]
 [ 250 1175 1400  846  488  136    7]
 [  44  287  471  601  502  211   13]
 [   6   56   94  187  337  191   22]
 [   2    4   16   44   81  111   18]
 [   0    1    4    9   20   39   10]]
